package io.github.loomforge.jtg.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a Java {@code record} for TypeScript type generation.
 *
 * <p>When the {@code jtg:generate} Maven goal is executed, JTG will scan
 * for all records annotated with {@code @TsRecord} and emit a corresponding
 * {@code .ts} file next to the {@code .java} source file.</p>
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * @TsRecord
 * public record User(String name, int age, boolean active) {}
 * }</pre>
 *
 * <p>Generates {@code User.ts} in the same directory:</p>
 * <pre>{@code
 * // Generated by JTG - do not edit manually
 * export interface User {
 *   name: string;
 *   age: number;
 *   active: boolean;
 * }
 * }</pre>
 *
 * <h2>Options</h2>
 * <ul>
 *   <li>{@link #exportName()} – override the TypeScript type name (defaults to the record name)</li>
 *   <li>{@link #asType()} – emit a {@code type} alias instead of an {@code interface}</li>
 * </ul>
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface TsRecord {

    /**
     * Override the exported TypeScript identifier.
     * Defaults to {@code ""} which means "use the Java record name".
     */
    String exportName() default "";

    /**
     * When {@code true}, emits a TypeScript {@code type} alias instead of an {@code interface}.
     *
     * <pre>{@code
     * // interface (default)
     * export interface User { ... }
     *
     * // type alias (asType = true)
     * export type User = { ... };
     * }</pre>
     */
    boolean asType() default false;
}
