package io.github.loomforge.jtg.plugin;

import io.github.loomforge.jtg.plugin.RecordParser.Component;
import io.github.loomforge.jtg.plugin.RecordParser.RecordDefinition;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generates a TypeScript {@code .ts} file from a {@link RecordDefinition}.
 * The output file is placed in the same directory as the source {@code .java} file.
 */
public final class TsEmitter {

    private static final DateTimeFormatter TIMESTAMP_FMT =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private TsEmitter() {}

    /**
     * Writes a {@code <RecordName>.ts} file next to the Java source file.
     * If the definition has dependencies (sibling records referenced by its components),
     * they are emitted first in the same file.
     *
     * @param def the parsed record definition (may include dependencies)
     * @return the path of the generated TypeScript file
     * @throws IOException if the file cannot be written
     */
    public static Path emit(RecordDefinition def) throws IOException {
        Path tsFile = def.sourceFile().resolveSibling(def.recordName() + ".ts");
        String content = render(def);
        Files.writeString(tsFile, content, StandardCharsets.UTF_8);
        return tsFile;
    }

    // -------------------------------------------------------------------------

    public static String render(RecordDefinition def) {
        StringBuilder sb = new StringBuilder();

        // Header comment
        sb.append("// Generated by JTG on ")
          .append(LocalDateTime.now().format(TIMESTAMP_FMT))
          .append("\n");
        sb.append("// Source: ").append(def.sourceFile().getFileName()).append("\n");
        sb.append("// Do not edit this file manually - changes will be overwritten.\n");

        // Emit dependency interfaces first (in dependency order, no header per dep)
        for (RecordDefinition dep : def.dependencies()) {
            sb.append("\n");
            renderType(dep, sb);
        }

        // Emit the annotated record itself
        sb.append("\n");
        renderType(def, sb);

        return sb.toString();
    }

    private static void renderType(RecordDefinition def, StringBuilder sb) {
        List<Component> components = def.components();

        if (def.asType()) {
            sb.append("export type ").append(def.exportName()).append(" = {\n");
            for (Component c : components) {
                sb.append("  ").append(c.name()).append(": ")
                  .append(TypeMapper.toTypeScript(c.type())).append(";\n");
            }
            sb.append("};\n");
        } else {
            sb.append("export interface ").append(def.exportName()).append(" {\n");
            for (Component c : components) {
                sb.append("  ").append(c.name()).append(": ")
                  .append(TypeMapper.toTypeScript(c.type())).append(";\n");
            }
            sb.append("}\n");
        }
    }
}
